import { CartProvider } from '@/context/CartProvider';
import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';

// вопрос по Head, должен ли он быть разным на разных страницах, например ключевые слова
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Dream day</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <meta keywords={'шары, композиции' + keywords} /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CartProvider>
        <Component {...pageProps} />
      </CartProvider>
    </>
  );
}
