import { CartProvider } from '@/context/CartProvider';
import '@/styles/global.scss';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import 'dayjs/locale/ru';
import { ThemeProvider } from '@mui/material';
import type {} from '@mui/x-date-pickers/themeAugmentation';
import { theme } from '@/context/clockTheme';

// вопрос по Head, должен ли он быть разным на разных страницах, например ключевые слова
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Dream day</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <meta keywords={'шары, композиции' + keywords} /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LocalizationProvider dateAdapter={AdapterDayjs} adapterLocale='ru'>
        <ThemeProvider theme={theme}>
          <CartProvider>
            <Component {...pageProps} />
          </CartProvider>
        </ThemeProvider>
      </LocalizationProvider>
    </>
  );
}
