import Head from 'next/head';
import Link from 'next/link';

export default function Cart() {
  return (
    <>
      <Head>
        <title>Dream day</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Link href='/'>Главная</Link>
        <Link href='/shop'>Магазин</Link>
        <Link href='/cart'>Корзина</Link>
      </div>
      <div>
        <p>Тут магазин</p>
      </div>
    </>
  );
}
